### ISSUE TITLE
GrapheneOS / Android 12 - Notification

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Wasted#18] opened 2022-06-06 20:21 UTC
When I use wasted on grapheneos and I send the famous code in an application that displays notifications, nothing happens and the phone does not wipe.

On the other hand, all the other functions, with duress, airplane mode etc. work perfectly.

Is it not necessary to add a request for authorization so that Wasted is the right to read the notifications?

**Comment by x13a** [comment] 2022-06-11 17:51
You have to grant Wasted the ability to read notifications after activating
notification trigger.

**Comment by xyz-nobody** [comment] 2022-06-12 11:46
I have given all the permissions, but impossible it does not work.

Or am I making a mistake?

I send the code on an application as a signal, it appears in the notifications of the phone but it does not wipe

**Comment by x13a** [comment] 2022-06-12 14:45
Please post a screenshot where you gave Wasted the permission to read a
device notifications.

**Comment by xyz-nobody** [comment] 2022-06-17 20:40
hello,

Here are all the permissions I found.

Can't we customize the code displayed because it's too long to copy lol?

In any case when I send a notification nothing happens.

thk for wasted i love this app

![signal-2022-06-17-203159_002](https://user-images.githubusercontent.com/6586244/174398132-e20ad5df-d2c8-4156-9eb8-172909291708.jpeg)
![signal-2022-06-17-203159_003](https://user-images.githubusercontent.com/6586244/174398134-47f47c9f-ba6a-448c-b300-1feeb08e5d26.jpeg)
![signal-2022-06-17-203159_004](https://user-images.githubusercontent.com/6586244/174398136-d5b3cf90-a251-47d3-b283-818dc747ed79.jpeg)
![signal-2022-06-17-203159_005](https://user-images.githubusercontent.com/6586244/174398139-d4019f16-c189-4685-be47-a9a5af7bff10.jpeg)

[
![signal-2022-06-17-203159_001](https://user-images.githubusercontent.com/6586244/174398124-6a8b0ede-5140-4058-aed6-b36fa32847c1.jpeg)
](url)

**Comment by x13a** [comment] 2022-06-25 21:20
@xyz-nobody , @RealJTG I can not reproduce this. Open _Device and app notifications_ > Wasted. Check that all checkboxes (Ongoing, Conversations..) are checked, open allowed apps on the bottom, check that your messenger is checked there too. I have tested it recently on Google Pixel, Android 12.1 and Telegram. All is working.

**Comment by RealJTG** [comment] 2022-06-26 12:04
@x13a thanks for your time! Yes, I can confirm it works now, though setup process is quite complicated and things could go wrong in many ways.

**To summarize, steps to be performed:**

<details>
  <summary>1. Enable notification trigger in Wasted</summary>
  
![00](https://user-images.githubusercontent.com/930399/175811934-9fc8cf72-b8b9-48c1-aa4a-152036067335.png)  
</details>

<details>
  <summary>2. Turn on Wasted</summary>
  
![01](https://user-images.githubusercontent.com/930399/175811935-8a715f98-2c3e-4b13-a20e-bd3c50ea4a60.png)
</details>

<details>
  <summary>3. Grant device admin rights</summary>
  
![02](https://user-images.githubusercontent.com/930399/175811936-20e2e7a2-96cd-4b21-81fd-8c0d0da9ed1c.png)
</details>

<details>
  <summary>4. Go to device and app notifications</summary>
  
![Screenshot_20220626-145425](https://user-images.githubusercontent.com/930399/175812942-1069ce66-ed3a-49b5-aaa8-157094df3003.png)
</details>

<details>
  <summary>5. Allow notification access <i>and</i> tick all checkbokses</summary>
  
![Screenshot_20220626-145433](https://user-images.githubusercontent.com/930399/175812965-d92a17ad-0b40-486f-a309-d8628379480c.png) ![Screenshot_20220626-145441](https://user-images.githubusercontent.com/930399/175812963-bd3c2368-e9de-44c4-bd51-16340e7e2641.png)
</details>

<details>
  <summary>6. Ensure your messagner app allows message preview in notifications, for Telegram there's a bunch of settings</summary>
  
![05](https://user-images.githubusercontent.com/930399/175811940-c2afea35-1fc2-4cae-81fd-a89091bed153.png) ![06](https://user-images.githubusercontent.com/930399/175811941-e7546f65-80b3-41af-a1a3-9501581842f9.png)
</details>


If you later turn off Wasted (revoke device admin) and then turn on again (grant device admin), **you have to re-check "device and app notifications settings"**. Wasted seems to be still "allowed" to read notifications, but none of them were actually allowed.

<details>
  <summary>This was probably my case</summary>
  
![03](https://user-images.githubusercontent.com/930399/175812596-a9b9e897-d82d-4d55-bfbb-57125f7ff7b6.png)
![oops](https://user-images.githubusercontent.com/930399/175812741-f2c5c841-6fa2-497c-88c7-6dc39a696bcb.png)
</details>

**Comment by x13a** [comment] 2022-06-26 19:38
Good to know that, thx)

**Comment by xyz-nobody** [comment] 2022-06-27 17:59
Thk all its works

**Comment by x13a** [comment] 2022-06-28 01:08
OK, closing it, Thank you all)

**Closed by x13a** 2022-06-28 01:08 UTC
